stages:
  - check

check/android:
  stage: check
  script:
    - poetry install
    - poetry run python run-ci.py android
  tags: [linux]


check/ios:
  stage: check
  script:
    - security unlock-keychain -p ${DEFAULT_KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db
    - poetry install
    - poetry run python run-ci.py ios
  tags: [macos]


check/web:
  stage: check
  script:
    - poetry install
    - poetry run python run-ci.py web
  tags: [linux]
