include:
  project: TankerHQ/gitlab-ci-files
  file: /cache.yml
  ref: 428eae8953297125aff965e14d23b7c657d515e3

default:
  image: registry.gitlab.com/tankerhq/docker/node:latest
  before_script:
    - poetry -V
    - node -v
    - poetry install
    - poetry run python --version

stages:
  - check

check/web:
  extends: .python-yarn-cache
  stage: check
  script:
    - poetry install
    - poetry run python run-ci.py web
  tags:
    - linux
